name: Build Dockerfile and upload artifacts

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag mingw-build
      - name: Copy artifacts
        run: COMMAND=docker ./copy.sh
      - name: Upload artifats
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: "*.tar.zst"
