name: Build Dockerfile and upload artifacts

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          overprovision-lvm: true
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag mingw-build
      - name: Copy artifacts
        run: COMMAND=docker ./copy.sh
      - name: Upload x86_64 tarball
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-w64-mingw32.tar.zst
          path: x86_64-w64-mingw32.tar.zst
      - name: Upload i686 tarball
        uses: actions/upload-artifact@v4
        with:
          name: i686-w64-mingw32.tar.zst
          path: i686-w64-mingw32.tar.zst
