name: Build Dockerfile and upload artifacts

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mingw-build
    - name: Copy artifacts
      run: COMMAND=docker ./copy.sh
    - name: Upload artifats
      uses: actions/upload-artifact@v3
      with:
        name: dist-without-markdown
        path: "*.tar.zst"
