name: Build Dockerfile and realease artifacts

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          overprovision-lvm: true
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag mingw-build
      - name: Copy artifacts
        run: COMMAND=docker ./copy.sh
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*tar.zst"
